# Generated by Django 4.1.7 on 2023-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_statuslog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите количество гостей', verbose_name='Количество гостей'),
        ),
    ]
