# Generated by Django 4.1.7 on 2023-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_guests_booking_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('inwork', 'В работе'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('pending', 'Ожидает отмены другого бронирования')], default='inwork', help_text='Выберите статус бронирования', max_length=16, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('inwork', 'В работе'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('pending', 'Ожидает отмены другого бронирования')], max_length=16, verbose_name='Статус бронирования'),
        ),
    ]
