# Generated by Django 4.1.7 on 2023-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_status_alter_statuslog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtext',
            name='name',
        ),
        migrations.AddField(
            model_name='emailtext',
            name='type',
            field=models.CharField(blank=True, choices=[('prebooking', 'Заявка'), ('cancel', 'Отмена'), ('reminder', 'Напоминание')], help_text='Изменение этого поля может привести к сбою при отправке почты!', max_length=20, null=True, verbose_name='Тип шаблона'),
        ),
    ]
