volumes:
  nn_apartments_data:

networks:
  nn_apartments_network:

services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:alpine
    env_file: .env
    volumes:
      - nn_apartments_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [ 'CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}' ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 5s
    restart: unless-stopped
    networks:
      nn_apartments_network:

  backend:
    image: apartments-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nn_apartments_backend
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - POSTGRES_PORT=5432
    volumes:
      - .:/apartmentsNN
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic --no-input
        gunicorn backend.wsgi --bind 0.0.0.0:8000
    networks:
      nn_apartments_network:
    restart: unless-stopped

  scheduler:
    image: apartments-backend
    depends_on:
      - backend
    volumes_from:
      - backend
    command:
      - bash
      - -c
      - python jobs.py
    networks:
      nn_apartments_network:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/apartmentsNN
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      nn_apartments_network:
