# Generated by Django 4.1.7 on 2023-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('dateFrom__lt', models.F('dateTo'))), name='dateFrom_lte_dateTo', violation_error_message='Дата окончания бронирования не может быть раньше даты начала или совпадать с ней'),
        ),
    ]
