# Generated by Django 4.1.7 on 2023-03-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_statuslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Изменение статуса', 'verbose_name_plural': 'История статусов бронирования'},
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
