# Generated by Django 4.1.7 on 2023-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона для использования при отправке email', max_length=20, verbose_name='Название шаблона')),
                ('subject', models.CharField(help_text='Введите тему сообщения', max_length=200, verbose_name='Тема')),
                ('before_name', models.TextField(help_text='Введите текст письма до обращения к клиенту', verbose_name='Текст до обращения')),
                ('after_name', models.TextField(help_text='Введите текст письма после обращения до информации о бронировании', verbose_name='Текст после обращения до информации о бронировании')),
                ('after_booking_info', models.TextField(help_text='Введите текст письма после информации о бронировании', verbose_name='Текст после информации о бронировании')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
    ]
