# Generated by Django 4.1.7 on 2023-03-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_alter_comfort_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedcharacteristic',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailedCharacteristic', to='flats.apartment'),
        ),
    ]
