# Generated by Django 4.1.7 on 2023-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_alter_apartmentimage_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.PositiveSmallIntegerField(default=60, help_text='Введите общую площадь', verbose_name='Общая площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=3, help_text='Введите количество комнат', verbose_name='Количество комнат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='store',
            field=models.CharField(default=1, help_text='Введите этаж и этажность здания (например, 1 из 2)', max_length=16, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='year',
            field=models.PositiveSmallIntegerField(default=1917, help_text='Введите год постройки', verbose_name='Год постройки'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetailedCharacteristic',
        ),
    ]
