# Generated by Django 4.1.7 on 2023-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_apartment_area_apartment_rooms_apartment_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfort',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comfort',
            name='type',
        ),
        migrations.AddField(
            model_name='comfort',
            name='option',
            field=models.CharField(choices=[('wi-fi', 'Бесплатный Wi-Fi'), ('parking', 'Бесплатная общественная парковка поблизости')], default='wi-fi', help_text='Выберите опцию комфорт', max_length=128, verbose_name='Опция комфорт'),
        ),
    ]
