# Generated by Django 4.1.7 on 2023-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_apartment_owner_alter_apartment_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='url',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0, help_text='Введите широту', verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0, help_text='Введите долготу', verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
