# Generated by Django 4.1.7 on 2023-03-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('shortCharacteristic', models.CharField(max_length=512)),
                ('price', models.PositiveIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('desc', models.CharField(max_length=512)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flats.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=128)),
                ('altName', models.CharField(max_length=256)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flats.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', models.CharField(max_length=512)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed', to='flats.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.apartment')),
            ],
        ),
    ]
