# Generated by Django 4.1.7 on 2023-03-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfort',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comfort', to='flats.apartment'),
        ),
    ]
