# Generated by Django 4.1.7 on 2023-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_alter_detailedcharacteristic_apartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Апартаменты', 'verbose_name_plural': 'Список апартаментов'},
        ),
        migrations.AlterModelOptions(
            name='comfort',
            options={'verbose_name': 'Опция комфорт', 'verbose_name_plural': 'Список опций комфорт'},
        ),
        migrations.AlterModelOptions(
            name='detailedcharacteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Список характеристик'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Список фотографий'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Расположение', 'verbose_name_plural': 'Список расположений'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(help_text='Введите адрес апартаментов', max_length=512, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='capacity',
            field=models.PositiveSmallIntegerField(help_text='Введите максимальную вместительность', verbose_name='Максимальная вместительность'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(help_text='Введите описание апартаментов', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(help_text='Введите название апартаментов', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.PositiveIntegerField(help_text='Введите цену апартаментов', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='shortCharacteristic',
            field=models.CharField(help_text='Введите короткое описание через запятую для отображения под названием апартаментов', max_length=512, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(help_text='Введите заголовок для части описания апартаментов', max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='comfort',
            name='description',
            field=models.CharField(help_text='Введите описание опции комфорт', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='comfort',
            name='type',
            field=models.CharField(help_text='Введите тип опции комфорт', max_length=128, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='detailedcharacteristic',
            name='data',
            field=models.CharField(help_text='Введите значение характеристики', max_length=512, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='detailedcharacteristic',
            name='name',
            field=models.CharField(help_text='Введите название характеристики', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='altName',
            field=models.CharField(blank=True, help_text='Введите альтернативное название', max_length=256, null=True, verbose_name='Альтернативное название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='Введите название фотографии', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(help_text='Выберите файл с изображением', upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.CharField(help_text='Введите описание расположения через запятую для отображением под заголовком расположения', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='url',
            field=models.URLField(help_text='Введите ссылку на карты', verbose_name='Ссылка на карты'),
        ),
    ]
