# Generated by Django 4.1.7 on 2023-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_mainpage_remove_image_apartment_mainpagesliderimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'ordering': ['group'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Список фотографий'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mainpagesliderimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='group',
            field=models.SmallIntegerField(blank=True, help_text='Введите целое число (можно отрицательное), которое будет использованно для сортировки групп', null=True, verbose_name='Номер группы'),
        ),
    ]
