# Generated by Django 4.1.7 on 2023-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_alter_comfort_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfort',
            name='option',
            field=models.CharField(choices=[('wi-fi', 'Бесплатный Wi-Fi'), ('parking', 'Бесплатная общественная парковка поблизости'), ('TV', 'Телевизор'), ('appliances', 'Вся необходимая бытовая техника'), ('linens', 'Постельное белье/полотенца'), ('key', 'Бесключевой доступ'), ('view', 'Вид на реку'), ('bathhouse', 'Сауна (оплачивается отдельно)'), ('entrance', 'Отдельный вход'), ('tea/coffee', 'Чай/кофе')], default='wi-fi', help_text='Выберите опцию комфорт', max_length=128, verbose_name='Опция комфорт'),
        ),
    ]
